project:
  type: website
  output-dir: _site

website:
  title: "Nicola Borri"
  site-url: "https://nborri1.github.io"
  description: "Academic website of Nicola Borri, Associate Professor of Finance at Luiss University."
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    title-block-style: none
