project:
  type: website
  output-dir: _site
  resources:
    - CNAME
    - assets/policy-media/public-web/

website:
  title: "Nicola Borri"
  site-url: "https://www.nicolaborri.com"
  description: "Official website of Nicola Borri, Associate Professor of Finance and Lian Group Chair in Blockchain Technology and Fintech at Luiss University."
  search: false

format:
  html:
    theme: cosmo
    css: site.css
    toc: false
    page-layout: full
    title-block-style: none
